# -*- coding: utf-8 -*-
"""Spam_Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rl7DuEw1bePrnjEf491FRRDwmvMtiK4T
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

df=pd.read_csv("/content/spam.csv")
df.head()

from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
x = vectorizer.fit_transform(df['Message'])
x

len(x.toarray())

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,df['Category'],test_size=0.25)

from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(x_train,y_train)

predic=model.predict(x_test)

from sklearn.metrics import classification_report
cr = classification_report(predic,y_test)
print(cr)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(predic,y_test)
print(cm)

import seaborn as sns
sns.heatmap(cm,annot=True,fmt='d',xticklabels=['not spam','spam'],yticklabels=['not spam','spam'])

